title: Nikolas Rieble
description: "Nikolas Rieble â€” leading teams, writing about software engineering."
url: "https://rieble.com"
author: Nikolas Rieble
permalink: /blog/:title/
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
include:
  - CNAME

defaults:
  - scope:
      path: ""
    values:
      image: /avatar.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
